name: Archive British Pathe

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Install Internet Archive CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install internetarchive

    - name: Archive URL
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        url="https://www.britishpathe.com/asset/$(($RUN_NUMBER + 36000))/"
        ia-capture $url --outlinks

    - name: Archive outlinks
      run: |
        outlinks=$(ia-search "source:$url" --field identifier | awk 'NR>1')
        for link in $outlinks; do
          ia-capture "https://web.archive.org/web/$link" --outlinks
        done
