name: Update README

# code copied from example on Wiki

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Archive URL
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        curl -sS "https://web.archive.org/save/https://www.britishpathe.com/asset/$(($RUN_NUMBER + 36000))"
        echo "https://web.archive.org/save/https://www.britishpathe.com/asset/$(($RUN_NUMBER + 100000))"
