name: Update README

# code copied from example on Wiki

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Archive URL
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        curl -sS "https://web.archive.org/save/https://www.britishpathe.com/asset/$(($RUN_NUMBER + 36000))"
        echo "LINK:"
        echo "https://web.archive.org/save/https://www.britishpathe.com/asset/$(($RUN_NUMBER + 36000))"

    - name: install
      run: |
        sudo apt-get install -y lynx
        
    - name: outlinks
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        # Extract outlinks from the webpage
        outlinks=$(lynx -dump -listonly "https://www.britishpathe.com/asset/$(($RUN_NUMBER + 36000))" | grep -o 'https\?://[^[:space:]]*')
        
        # Archive each outlink using the Wayback Machine API
        for link in $outlinks; do
          curl -sS "https://web.archive.org/save/$link"
          echo "LINK:"
          echo "https://web.archive.org/save/$link"
        done
