name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Extract and archive video URL
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        python <<EOF
        import requests

        def check_archive_status(url):
            api_url = f"http://archive.org/wayback/available?url={url}"
            response = requests.get(api_url)
            data = response.json()
            return data['archived_snapshots'] != {}

        def archive_url(url):
            if check_archive_status(url):
                print(f"Already archived: {url}")
                return

            archive_url = f"https://web.archive.org/save/{url}"
            response = requests.get(archive_url)
            print(f"Newly archived: {url}")
            print(f"Archive URL: {archive_url}")

        def find_video_source(html):
            video_start = html.find("<video")
            video_end = html.find("</video>", video_start)
            if video_start == -1 or video_end == -1:
                return None

            video_tag = html[video_start:video_end]
            src_start = video_tag.find('src="') + 5
            src_end = video_tag.find('"', src_start)
            
            return video_tag[src_start:src_end]

        run_number = int("$RUN_NUMBER")
        url = f"https://www.britishpathe.com/asset/{run_number + 52000}"
        
        response = requests.get(url)
        html_content = response.text
        
        video_source = find_video_source(html_content)
        
        if video_source:
            print(f"Found video source: {video_source}")
            archive_url(video_source)
        else:
            print("No video source found")
        
        # Archive the main page as well
        archive_url(url)
        EOF
